return {}

-- Basic plugin, no options.
-- Requires a command to be run at runtime to set the colorscheme
-- via `config = function()...`.
--
-- return {
--     "folke/tokyonight.nvim",
--     lazy = false,
--     priority = 1000,
--     opts = {},
--     config = function()
--         vim.cmd[[colorscheme tokyonight-moon]]
--     end,
-- }

-- Basic plugin with dependencies and a specific branch.
-- Lazy loaded to activate only on a specific keypress.
-- This works well for very fast to load plugins.
--
-- return {
--     "nvim-neo-tree/neo-tree.nvim",
--     branch = "v3.x",
--     dependencies = {
--       "nvim-lua/plenary.nvim",
--       "nvim-tree/nvim-web-devicons",
--       "MunifTanjim/nui.nvim",
--     },
--     -- Keybinds as a cmd string, strings mess up syntax highlighting but
--     -- allows for lazy loading the plugin
--     keys = {
--         {"<leader>e", ":Neotree toggle<CR>", desc = "Toggle filetree explorer"}
--     },
-- }

-- Keybinds set in config, this allows syntax highlighting
-- but the plugin is run at nvim startup, not lazyloaded
--return {
--  {
--    -- Make vim.ui.select api use telescope by default
--    "nvim-telescope/telescope-ui-select.nvim",
--  },
--  {
--    "nvim-telescope/telescope.nvim",
--    branch = "0.1.x",
--    dependencies = { "nvim-lua/plenary.nvim" },
--    config = function()
--      require("telescope").setup({
--        extensions = {
--          ["ui-select"] = {
--            require("telescope.themes").get_dropdown({}),
--          },
--        },
--      })
--      local builtin = require("telescope.builtin")
--      vim.keymap.set("n", "<leader>sf", builtin.find_files, { desc = "[S]earch for [f]iles" })
--      vim.keymap.set("n", "<leader>sg", builtin.live_grep, { desc = "[S]earch via [g]rep" })
--
--      require("telescope").load_extension("ui-select")
--    end,
--  },
--}
